---
#Main mysql tasks file

- name: Install dependencies for ubuntu 16.04 and earlier
  apt:
    name: python-mysqldb
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int < 18

- name: Install dependencies for ubuntu 18.04 and on
  apt:
    name:
      - python3-mysqldb
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int >= 18

- name: Install PIP dependencies for ubuntu 18.04 and on
  pip:
    name: PyMySQL
    state: present
    executable: pip3
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int >= 18

- include: mariadb.yml
  when:
    - mysql_variant == "MariaDB"

- include: mysql.yml
  when:
    - mysql_variant == "MySQL"

- include: replication_master.yml
  when: mysql_replication and mysql_replication_role == "Master"

- include: replication_slave.yml
  when: mysql_replication and mysql_replication_role == "Slave"
