---
#Main mysql tasks file

- name: Install dependencies for ubuntu
  apt:
    name:
      - python3-mysqldb
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"

- name: Install PIP dependencies
  pip:
    name: PyMySQL
    state: present
    executable: pip3
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"

- ansible.builtin.include_tasks: mariadb.yml
  when:
    - mysql_variant == "MariaDB"

- ansible.builtin.include_tasks: mysql.yml
  when:
    - mysql_variant == "MySQL"

- ansible.builtin.include_tasks: replication_master.yml
  when: mysql_replication and mysql_replication_role == "Master"

- ansible.builtin.include_tasks: replication_slave.yml
  when: mysql_replication and mysql_replication_role == "Slave"
