---
#Mariadb tasks

- name: Add mariadb repo key - Debian
  apt_key:
    keyserver: "{{ mariadb_key_server }}"
    id: "{{ mariadb_key_id }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add mariadb repo - Debian
  apt_repository:
    repo: "{{ mariadb_repo }}"
    state: present
    mode: 0644
  when: ansible_os_family == "Debian"

- name: Install mariadb - Debian
  apt:
    name: mariadb-server
    state: latest
    force: yes
  when: ansible_os_family == "Debian"

- name: Configure mariadb
  template:
    src: "mysql_config"
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mysqld
- meta: flush_handlers

- name: Set service type
  set_fact:
    mysql_service: mysql

- name: Start mysql
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes
