---
- name: Install MySQL
  apt:
    name: mysql-server
    state: latest
    force: yes

- name: Configure MySQL
  template:
    src: "mysql_config"
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mysql
- meta: flush_handlers

- name: Set service type
  set_fact:
    mysql_service: mysql

- name: Start mysql
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes
