---
#Main mysql handlers file

- name: Restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Restart mariadb
  service:
    name: mariadb
    state: restarted
    enabled: yes
